package com.mipt.bank;

public enum CoinTransactionType {
  INITIAL_GRANT,
  DAILY_REWARD,
  QUIZ_REWARD,
  TRUE_FALSE_REWARD,
  GAME_ENTRY,
  GAME_PAYOUT,
  BET_PLACED,
  BET_REFUND,
  PREMIUM_PURCHASE,
  MANUAL_ADJUSTMENT
}
