spring.application.name=QuizAI

# Конфигурация сервера
server.port=8080

# Настройки БД для DbService
# Параметры для Docker-контейнера PostgreSQL
# Перед запуском приложения убедитесь, что контейнер Docker запущен
app.database.url=jdbc:postgresql://localhost:5432/quizai
app.database.user=postgres
app.database.password=postgres

spring.web.resources.static-locations=classpath:/templates/
spring.mvc.static-path-pattern=/**

# Настройки Kafka для генерации вопросов ML
spring.kafka.bootstrap-servers=localhost:9092
app.kafka.topic.ml-question-requests=ml-question-requests
spring.kafka.consumer.group-id=question-generation-consumer-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

